### ISSUE TITLE
I can't switch weapons/fire alt

### ISSUE THREAD

**Issue by KLash17** [CultOfJakito/UltraTelephone#17]
I wanted to try this mod out and there is one problem, I can't switch weapons, their variations, or even fire the alts like tossing a coin. Can this be fixed or is it a mod in my menu that is causing it?

**Comment by wafflethings** [comment]
intentional feature ;3 
have fun

**Comment by KLash17** [comment]
I know that it does it at random, but It doesn't do it for the entire level

**Comment by Hydraxous** [comment]
Why would you want to switch weapons?

**Comment by KLash17** [comment]
Ok doing more research I found out that most of the things in the mod don't work Like the random damage, the coins, even the "UWU get jammed" related things are broken

**Comment by Protract-123** [comment]
yeah new version kinda broke stuff

**Comment by Doddged** [comment]
> 

almost as if i want to experience the actually funny things that people have put into the mod without having to go to the terminal every 20 seconds.

ruins half of the damn mod and isn't even funny.

i created a github account specifically to be upset over the internet.

like i get the entire point of the mod is to make things shitty, but a low effort change that blocks other features is just so brain dead i can't get over it.

come on man.

**Comment by TeamDoodz** [comment]
skill issue 👍

**Comment by Temperz87** [comment]
Oh I'm sorry, LOW EFFORT? DO YOU KNOW HOW LONG WE SPENT PROGRAMMING THAT CHANGE? I'LL HAVE EYOU KNOW THAT I GRADUATED TOP OF MY CLASS IN THE NAVY SEALS, AND I HAVE OVER 100 CONFIREMD STWAR ON MY EE w E E@Q_E JWQ_(OEJWQOPEOPQE

**Comment by wafflethings** [comment]
i had to code for hundreds of grueling hours to create this feature. i suffered through agony comparable to damnation in hell, individually inputting CIL instructions through my keyboard. i did not sleep, eat, or drink, for a week; and i was drawn towards it, tempted by the devil, to give up, but i continued, as i knew it was my calling. to call my magnum opus of programming - a cultural masterpiece comparable to the mona lisa, or the creation of adam - a 'low effort change' is disrespect to a level that i could never imagine.

**Comment by Protract-123** [comment]
later doodz, first i have to mention how many cil instructions i had to manually type, after all the entire mod is made in cil just for the funnies, so honestly this guy truly has a skill issue

**Comment by wafflethings** [comment]
doodz

when god sings with his creations you will not be part of the choir

**Comment by Hydraxous** [comment]
[![Watch the video](https://media.tenor.com/v6j3qu9ZmMIAAAAM/funny-cat.gif)]

**Comment by wafflethings** [comment]
🥺

**Comment by Hydraxous** [comment]
> > 
> 
> almost as if i want to experience the actually funny things that people have put into the mod without having to go to the terminal every 20 seconds.
> 
> ruins half of the damn mod and isn't even funny.
> 
> i created a github account specifically to be upset over the internet.
> 
> like i get the entire point of the mod is to make things shitty, but a low effort change that blocks other features is just so brain dead i can't get over it.
> 
> come on man.

This feature has now been removed as of [Release 1.1.5](https://github.com/CultOfJakito/UltraTelephone/releases/tag/1.1.5)
